name: Build Linux ELF
on: [push]

permissions:
  contents: write # Permiso crítico para que el bot pueda subir el .elf

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build with Nuitka
        # Compilamos y forzamos el nombre del binario
        run: python -m nuitka --onefile --standalone --output-filename=obfuscator obfuscator.py

      - name: Commit and Push ELF to Repository
        run: |
          # Configuramos tu identidad para el commit
          git config --global user.name "GraviDuck"
          git config --global user.email "asier.adell.diaz@gmail.com"
          
          # Renombramos el archivo generado por Nuitka a .elf
          mv obfuscator.bin obfuscator.elf || mv obfuscator obfuscator.elf
          
          # Añadimos el .elf al repositorio
          git add obfuscator.elf
          
          # Hacemos el commit. El [skip ci] evita que GitHub entre en bucle infinito
          git commit -m "Auto-update obfuscator.elf [skip ci]" || echo "Sin cambios detectados"
          
          # Subimos el archivo a la rama main
          git push origin main
