name: Build Executables
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false # Para que si Windows falla, Linux siga adelante
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build with Nuitka
        run: python -m nuitka --onefile --standalone obfuscator.py

      - name: Rename Linux Output
        if: runner.os == 'Linux'
        # Aquí es donde ocurre la magia para que sea .elf
        run: mv obfuscator.bin obfuscator.elf || mv obfuscator obfuscator.elf

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binarios-${{ matrix.os }}
          path: |
            obfuscator.exe
            obfuscator.elf
